package com.signal.Signal.service;

import com.google.genai.Client;
import com.google.genai.types.*;
import com.signal.Signal.dto.SignalResponse;
import com.signal.Signal.websocket.SignalSocketHandler;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Lazy;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.WebSocketSession;

import java.time.Instant;
import java.util.Arrays;
import java.util.Base64;
import java.util.Collections;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class SignalBoardService {

    private final Client geminiClient;

    @Lazy
    private final SignalSocketHandler socketHandler;

    @Async
    public void generateDiagram(WebSocketSession session, String conversationContext) {
        sendLoadingSignal(session);

        String visualPrompt = """
            Visual prompt for software architecture:
            %s
            
            Style: Technical whiteboard, high contrast, specific icons (Postgres, Redis).
            Draw immediately.
        """.formatted(conversationContext);

        GenerateContentConfig config = GenerateContentConfig.builder()
                .responseModalities(Arrays.asList("IMAGE"))
                .temperature(0.4f)
                .build();


        int maxRetries = 3;
        for (int attempt = 1; attempt <= maxRetries; attempt++) {
            try {
                log.info("Gemini 3 Generation (Attempt " + attempt + ")...");

                GenerateContentResponse response = geminiClient.models.generateContent(
                        "gemini-3-pro-image-preview",
                        Content.builder().role("user").parts(Collections.singletonList(
                                Part.builder().text(visualPrompt).build()
                        )).build(),
                        config
                );

                if (extractAndSendImage(session, response)) return;

            } catch (Exception e) {
                if (e.getMessage().contains("429") || e.getMessage().contains("Resource exhausted")) {

                    long wait = 1000L * attempt;
                    log.warn("Quota (429). Retrying in " + wait + "ms...");
                    try { Thread.sleep(wait); } catch (InterruptedException ignored) {}
                } else {
                    log.error("Critical Error: " + e.getMessage());
                    break;
                }
            }
        }
        log.error("Failed to generate diagram after retries.");
    }

    private boolean extractAndSendImage(WebSocketSession session, GenerateContentResponse response) {
        return response.candidates().orElse(Collections.emptyList()).stream()
                .map(c -> c.content().orElse(null))
                .filter(content -> content != null)
                .map(content -> content.parts().orElse(Collections.emptyList()))
                .flatMap(List::stream)
                .filter(part -> part.inlineData().isPresent())
                .map(part -> part.inlineData().get().data().orElse(null))
                .filter(bytes -> bytes != null && bytes.length > 0)
                .findFirst()
                .map(imageBytes -> {
                    String base64 = Base64.getEncoder().encodeToString(imageBytes);
                    SignalResponse responseObj = SignalResponse.builder()
                            .type(SignalResponse.SignalType.IMAGE_GENERATED)
                            .title("Live Architecture Board")
                            .description("Generated by Nano Banana Pro")
                            .imageBase64(base64)
                            .timestamp(Instant.now())
                            .confidence(1.0)
                            .build();
                    socketHandler.sendSignal(session, responseObj);
                    log.info("Diagram Sent!");
                    return true;
                })
                .orElse(false);
    }

    private void sendLoadingSignal(WebSocketSession session) {
        try {
            SignalResponse loading = SignalResponse.builder()
                    .type(SignalResponse.SignalType.IDLE)
                    .title("Generating Board...")
                    .description("Gemini 3 is drawing the architecture...")
                    .timestamp(Instant.now())
                    .confidence(1.0).build();
            socketHandler.sendSignal(session, loading);
        } catch (Exception e) {}
    }
}